databases:
  - name: pidgeon
    plan: free
    databaseName: pidgeon
    user: pidgeon

services:
  - type: web
    name: pidgeon
    plan: free
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pidgeon
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false